let ACTION_TYPE = {
  CURRENT_SCREEN: 'CURRENT_SCREEN',
  SET_LOGIN: 'SET_LOGIN',
  SET_USER: 'SET_USER',
  GET_REFERRAL: 'GET_REFERRAL',
  ACTIVE_MANDATE: 'ACTIVE_MANDATE',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CALENDAR: 'CALENDAR',
  CALENDAREVE: 'CALENDAREVE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SAVE_REFERRAL_LIST: 'SAVE_REFERRAL_LIST',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  PORTFOLIO: 'PORTFOLIO',
  SET_FORUM_CATEGORY: 'SET_FORUM_CATEGORY',
  SET_SELECTED_FORUM: 'SET_SELECTED_FORUM',
  SET_SELECTED_FORUM_QUES: 'SET_SELECTED_FORUM_QUES',
  STATE_LIST: 'STATE_LIST',
  MY_PROFILE: 'MY_PROFILE',
  SET_QUESTION_FOR_RESPONSE: 'SET_QUESTION_FOR_RESPONSE',
  GET_QUESTION: 'GET_QUESTION',
  AUTH_RESET: 'AUTH_RESET',
  FORUM_RESET: 'FORUM_RESET',
  HOME_RESET: 'HOME_RESET',
  RESET_FIRST_TIME : 'RESET_FIRST_TIME'
};

module.exports = ACTION_TYPE;
